name: 🚀 Release Tokens

on:
  release:
    types: [created]

jobs:
  publish-package:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@tomasfrancisco"

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Publish
        run: pnpm publish --report-summary --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SECRET_GITHUB_REGISTRY_TOKEN }}
