name: ✨ Release

on:
  push:
    paths:
      - packages/alpha

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: ✨ Release
    runs-on: uubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@tomasfrancisco"

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to Registry
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SECRET_GITHUB_REGISTRY_TOKEN }}
