name: 🚀 Release Tokens

on:
  release:
    types: [created]

jobs:
  publish-package:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish --access=restricted --report-summary --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.SECRET_GITHUB_REGISTRY_TOKEN}}
